default_platform(:ios)

####################################################################################################
####################################################################################################

##############
# Test lanes #
##############

desc "Runs app's unit tests in the specified device."
desc "Usage example: fastlane unit_test device:'iPhone 8'"
lane :unit_test do |options| 
  raise "Missing 'device' parameter. Usage: fastlane unit_test device:DEVICE" unless options[:device]
  scan(
      scheme: "tvmazetechtestTests",
      device: options[:device],
      clean: true,
      disable_concurrent_testing: true
  )
end

desc "Runs app's ui unit tests in the specified device."
desc "Usage example: fastlane ui_test device:'iPhone 8'"
lane :ui_test do |options| 
  raise "Missing 'device' parameter. Usage: fastlane ui_test device:DEVICE" unless options[:device]
  scan(
      scheme: "tvmazetechtestUITests",
      device: options[:device],
      clean: true,
      disable_concurrent_testing: true
  )
end

###############
# Build lanes #
###############

desc "Builds the app to make sure there are no breaking changes. No tests are executed."
desc "Usage example: fastlane build_framework"
lane :compile_app do |options|
  xcbuild(
    scheme: "tvmazetechtest",
    sdk: "iphonesimulator",
    clean: true
  )
end
